### ISSUE TITLE
thread safety of callbacks and server config instances

### ISSUE THREAD

**Issue by icing** [abetterinternet/mod_tls#2]
In Rust, the trait `Sync` indicates that an object is thread-safe, e.g. can be called concurrently. When implementing this trait for an object, it extends to all its members. In `rustls` the `ServerConfig` and `ServerSession` implement this trait.

This means when a `C` client such as `mod_tls` installs a callback in a config or session, it needs to assume to be invoked concurrently and protect itself via `mutex` or other measure.

While this works, it seems excessive for callbacks on a particular `ServerSession`, e.g. a TLS connection, since all state progression of that connection happens in one thread (not the same every time, but only one at a time.).

The questions are

1. can `rustls` give some assertion that callbacks installed on a not-shared `ServerConfig` (e.g. only a single `ServerSession ` made with it) will not be run concurrently?
2. `ServerConfig`s in `rustls` are intended to be few and shared often, as they are relatively expensive. Is this also true if configs are `clone()`ed and then only a new parameters adjusted? Or is this a good way forward?
3. If cloning is considered expensive, the creation of a `ServerSession` needs to allow for more parameters to be adjustable. As for the background to this:

There is always a set of configured configurations created when the server loads. These are virtual hosts, their certificates, protocol settings, client auth etc. For these, `mod_tls` creates a `ServerConfig` each. During the `ClientHello` processing, the SNI hostname commonly selects on of these configs.

The server then triggers its internal `ALPN` negotiation and the result of that, the selected protocol, can be very dynamic. The `http2` protocol handler might select `h2` or abstain. The ACME protocol handler might override and force the `acme-tls/1`. The client might bring in something totally new and the server might have in installed module that can handle it. In short, `mod_tls` cannot prepare all possible `ServerConfig` variations in advance.

On top of that, the ALPN internal negotiation might change other things as well. The ACME `tls-alpn-01` challenge will override the installed certificates and replace them with a new, dynamically created one. This cannot be prepared in advance.

For these reasons, the flow in `mod_tls` is now as follows:

```
Apache start -> virtual hosts -> ServerConfig per vhost with static certs, protocol version etc.
Client connect -> ClientHello analysis *)
   -> SNI check -> vhost select, ServerConfig base selected
   -> selected ServerConfig cloned
      -> ALPN internally negotiated and configured on clone
      -> certificate overrides set on clone
      -> clone to ServerSession
```

*) the ClientHello analysis is a bit more complicated but that will be addressed by https://github.com/ctz/rustls/issues/89.

/CC @ctz @djc @jsha

**Comment by jsha** [comment]
> can rustls give some assertion that callbacks installed on a not-shared ServerConfig (e.g. only a single ServerSession made with it) will not be run concurrently?

I'm pretty sure this is the case _currently_ based on the implementation of rustls, and you are proposing that rustls could make that a formal part of the documentation, right? Like "`ResolvesServerCert::resolve()` will be called at most once for each `ServerSession`?" That seems like a reasonable thing to ask for, but if ctz/rustls#89 is resolved as proposed (with an `Acceptor`), that will become unneeded.

Another way to make sure the callback is thread-safe is to ensure that it only ever reads data (e.g. from `userdata`), and that nothing else modifies that data for the duration of the `ServerSession` (which is quite short in your intended deployment). Is that a feasible approach in your situation?

> ServerConfigs in rustls are intended to be few and shared often, as they are relatively expensive. Is this also true if configs are clone()ed and then only a new parameters adjusted? Or is this a good way forward?

I don't know for sure, but I _suspect_ based on looking at the code that clone()ing should be cheaper than constructing from scratch. The things that seem potentially expensive are setting up a `ResolvesServerCert`, and `ClientCertVerifier` and so on.

**Comment by icing** [comment]
We will have more callbacks in the future, like for session storage. It is just necessary to document in the C API what the requirements are not only regarding memory use, but also thread safety.

**Comment by djc** [comment]
I still find the behavior much easier to reason about if it comes with examples, so it's still useful to couch it in terms of more concrete things you want to do.

I still think you probably want to maintain just one `ServerConfig` (or only a few), and use something like [`ResolvesServerCertUsingSni`](https://github.com/ctz/rustls/blob/main/rustls/src/server/handy.rs#L151) to initialize the session. I think the `Acceptor` should definitely make that stuff easier -- we can also discuss making changes to `ServerConfig`'s capabilities in order to fit your use cases.


> 1. can rustls give some assertion that callbacks installed on a not-shared `ServerConfig` (e.g. only a single `ServerSession` made with it) will not be run concurrently?

rustls does not hide `ServerConfig`s anywhere or keeps a reference to them anywhere. If you constructed a `ServerConfig`, you hold the only reference to it, and there's nothing rustls can do with it. (This is part of Rust's ownership model.)

> 2. `ServerConfig`s in rustls are intended to be few and shared often, as they are relatively expensive. Is this also true if configs are `clone()`ed and then only a new parameters adjusted? Or is this a good way forward?

I would aim to have as few configs as reasonably possible. Any indication that you need more than a handful is probably worth an enhancement request on the rustls side. As for the exact costs, I think you should probably benchmark the construction costs (either from scratch or via `clone()`) and memory usage for yourself and see how relevant it is to your use case. I don't know exactly why Joe advertised them as expensive (by the nature of the language, Rust users are picky about performance, so even a few allocations might be expensive to them, even if they don't matter in the context of httpd).

> 3. If cloning is considered expensive, the creation of a ServerSession needs to allow for more parameters to be adjustable.

In my mind you can already implement your own [`ResolvesServerCert`](https://docs.rs/rustls/0.19.0/rustls/trait.ResolvesServerCert.html), which allows a `ServerConfig` quite a bit of flexibility in what certificate chain to select based on the data in the [`ClientHello`](https://docs.rs/rustls/0.19.0/rustls/struct.ClientHello.html) (SNI, ALPN and signature scheme). What other input parameters would you need?

**Comment by ctz** [comment]
I'd be happy to make some statements about threads in rustls documentation. Let me know if that's helpful. Things I have in mind are:

- rustls will not start threads by itself.
- leading from that, the threads you get called back on are only the threads that are calling into rustls ServerSession/ClientSession methods.

I think those two give you complete predictability about which threads callbacks will happen on?

**Comment by jsha** [comment]
I think that would be quite helpful.

**Comment by icing** [comment]
Thanks for clarifying this.
